package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"log"

	"github.com/wellalencarweb/challenge-clean-architecture/internal/infra/graph/model"
	"github.com/wellalencarweb/challenge-clean-architecture/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	dto := usecase.OrderInputDTO{
		ID:    input.ID,
		Price: float64(input.Price),
		Tax:   float64(input.Tax),
	}
	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         output.ID,
		Price:      float64(output.Price),
		Tax:        float64(output.Tax),
		FinalPrice: float64(output.FinalPrice),
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {

	log.Printf("GetAll Orders GraphQL")

	log.Printf("Coletando as ordens")
	// Buscando todas as ordens existentes. O retorno é uma struct que contém apenas um elemento: um slice de orders.
	orders, err := r.GetAllOrdersUseCase.GetAllOrders()
	if err != nil {
		log.Printf("Erro ao coletar as Orders do useCase (GraphQL): %s", err)
		return nil, err
	}

	// Slice que será utilizado para receber as ordens e retornar os valores
	var ordersModel []*model.Order

	//loop para adicionar todas as ordens no slice.
	for _, order := range orders.Orders {
		ordersModel = append(ordersModel, &model.Order{
			ID:         order.ID,
			Price:      order.Price,
			Tax:        order.Tax,
			FinalPrice: order.FinalPrice,
		})
	}

	// Retornando todas as orders utilizando o modelo de orders
	return ordersModel, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
